### ISSUE TITLE
Need to integrate with nuxt simple sitemap module

### ISSUE THREAD

**Issue by rolexta** [johannschopplich/nuxt-api-party#23]
### Describe the feature

Hi,

Currently i want to create a sitemap.xml with dynamic url that should fetch the data from every dynamic pages.

The issue is jsonPlaceholder is not defined, i already config the suit-party on nuxt.config

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Please provide a [minimal reproducible example](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) of the issue you've encountered.

**Comment by rolexta** [comment]
Hello, i want to do something loke on this documentation from nuxt-simple-sitemap

https://nuxt.com/modules/simple-sitemap#handling-dynamic-urls

Can i get an exmple with nuxt-apy-party?

Thankyou

**Comment by johannschopplich** [comment]
The API Party composables are only available during the component lifecycle. Nitro server routes don't have access to the Nuxt instance.

The intention of the API Party module is to mask your real API when using it in the frontend for requests in the client. Since you want to fetch data inside a server route, you actually don't need the API Party module, since your real API will never be exposed to the client. You can fetch your data directly. 

Hope that clarifies the use-cases of this module. 🙂

**Comment by johannschopplich** [comment]
@rolexta Actually, I have changed my opinion. The generated composables like `$myApi` should be available in Nitro routes as well.

This feature is available right now in v0.15.0! 🙂
