### ISSUE TITLE
Allow headers to pass-through to the response on the client 

### ISSUE THREAD

**Issue by 9M6** [johannschopplich/nuxt-api-party#25]
### Describe the feature

When using API-Party and making a request to a backend, default functionality should be for headers to pass-through to the client, and maybe have an ability filter them.

On the below images, we see one of the request responses using the native Fetch function sending a request directly to the endpoint, and the other using API Party.

I checked if any feature related to this issue existed in API Party but didn't find anything. 

![image](https://github.com/johannschopplich/nuxt-api-party/assets/61775571/3db2c9ea-add5-482e-bf3a-ce9911b1180e)
![image](https://github.com/johannschopplich/nuxt-api-party/assets/61775571/9445bbc4-467c-4669-b62f-c9034e822bf6)

If this is a non-feature, let me know how can I solve this in any other way.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Nice. This would probably be a great addition. 👍 PR always welcome.

**Comment by 9M6** [comment]
@johannschopplich Sorry for the late reply, I've been a bit busy.

Regarding the feature, I did not investigate at first if headers were returned or sent to the Final API endpoint, but what I had expected is that the headers that I would pass to the Proxy API would actually be forwarded to the Final API Endpoint, and likewise, when the backend is returning headers it would be returned back with the payload.

The API-Party should to me is simply a way to have a unified backend service, which delegates calls to different endpoints, though I believe the current interface of API party would be difficult to change and might break things, so I think having a specific configuration where a boolean property is defined in the config object which will `passthrough` the entire call form the client to the backend and would also return the call from the backend as if the call is made directly to the Final API Endpoint.

My expectations would be that the `Proxy` should never remove payloads from the backend, but only enhance them and build on top of it.

**Comment by 9M6** [comment]
Regarding the PR, I'll see if I can manage something, but I've been pretty busy lately, so it might take a while.

**Comment by johannschopplich** [comment]
Comment from @killjoy1221:
> When using the server handler, headers are not being forwarded from the API server to the client. I'm aware that headers are not normally accessible using the `$api` function, but they *are* when using `useApiData(..., { onResponse })` and via `FetchError.response`. Additionally, if an API sets a cookie, it will be unable to do it as the `Set-Cookie` header is discarded.

**Comment by killjoy1221** [comment]
I've started tinkering. I think the right way to go is to use `sendWebResponse` or `event.respondWith` to forward the fetch Response directly to the client. I'm able to use it with normal `fetch`, but when I use it with `$fetch.raw` I run into issues.

Without any preparation, piping the result of `$fetch.raw` to `event.resondWith()` will result in a `Type Error [ERR_INVALID_STATE]: Invalid state: The ReadableStream is locked`. I believe this is because ofetch consumes the body by default. Setting `responseType: 'stream'` in the $fetch options resolves this. Setting it to anything else will cause the error to reappear.

Unfortunately, now there's an error on the client. `TypeError: Decoding failed.`. This error doesn't happen on all endpoints.
