### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by psmoros** [johannschopplich/nuxt-api-party#28]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ohb00) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by johannschopplich** [comment]
Hi there, @psmoros!

Thanks for reaching out. I have added a [`SECURITY.md`](https://github.com/johannschopplich/nuxt-api-party/blob/main/.github/SECURITY.md) file. Feel free to drop me a line via the linked email.
Thanks in advance!

**Comment by johannschopplich** [comment]
Thank you very much for the report! It has been fixed in the latest release, [0.13.0](https://github.com/johannschopplich/nuxt-api-party/releases/tag/v0.13.0).

The security incident has also been added to the [`SECURITY.md`](https://github.com/johannschopplich/nuxt-api-party/blob/main/.github/SECURITY.md).
