### ISSUE TITLE
Error status code is always "500"

### ISSUE THREAD

**Issue by Robinrrr** [johannschopplich/nuxt-api-party#5]
Hey and thanks for your awesome nuxt module! I really like it.

Unfortunately, I have a small problem that I can not solve. No matter what status code I get back from my API. It always returns the error code 500.  Is there a way to get the correct status code?

`POST http://localhost:3000/api/__api_party/cms 500 (Failed to fetch from API endpoint "cms")`

But the correct status code should be 400

**Comment by johannschopplich** [comment]
Thanks for the flowers!

This is intentional – https://github.com/johannschopplich/nuxt-api-party/blob/906f1ece91b4a7e4b34858466a36db3214c87789/src/runtime/server.ts#L42.

As the idea of this module is to mask your real API by creating a Nuxt server proxy, we always throw a custom error if your API fails to deliver.

Now I don't get if you wish to retrieve the real status code returned by your API or if you think `500` is wrong. Cause in my opinion it should always throw `400` instead What do you think?

**Comment by johannschopplich** [comment]
Side note: The error thrown by your API is available via the `error` ref. Example usage:

```ts
const { data, error } = await useJsonPlaceholderData()

watchEffect(() => console.log(error.value.data))
```

**Comment by Robinrrr** [comment]
Thank you for your quick reply. Sorry that I did not answer so accurately. In my use case I have a contact form that I validate client side, but also on server side. I would like to differentiate if the API is Not reachable, or if the input is invalid. Based on that, I show different error messages. 

In my case, I get the error value `FetchError: 500 Failed to fetch from API endpoint "cms" (/api/__api_party/cms)` back (the function is called client-side). Is there a way i can get the real api response status code? Thanks again!

`const {error} = await useCmsData('/api/forms-contact', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
    },
    body: form.value,
});`

**Comment by johannschopplich** [comment]
Side note: `useCmsData` is intended more for data fetching inside templates. If using inside a function like when hitting the submit button, I would recommend to use `$cmsData` to directly retrieve the raw content instead of letting the data be wrapped in `data` and `error`. You can also just use `try {} catch {}` with it. Much easier to handle.

Have you followed my instructions above? You can retrieve the status code inside the `data` key.

**Comment by johannschopplich** [comment]
@Robinrrr Also, keep in mind that responses from `useCmsData` will be cached by default, while `$cmsData` responses are not. I've noted it in the documentation yesterday. The hash for the cache will be computed based on the path and fetch options provided.

**Comment by johannschopplich** [comment]
@Robinrrr I've come up with a better solution. `nuxt-api-party` 0.7.0+ will forward error responses – including `statusCode`, `statusMessage` as well as the API response body as `data` – to the client if your API fails to deliver.

**Example usage with `useJsonPlaceholderData()`**

```ts
const { data, error } = await useJsonPlaceholderData('not-found')
watchEffect(() => {
  console.error('statusCode:', error.value.statusCode)
  console.error('statusMessage:', error.value.statusMessage)
  console.error('data:', error.value.data)
})
```

**Example usage with `$jsonPlaceholder()`**

```ts
function onSubmit() {
  try {
    const response = await $jsonPlaceholder('not-found', {
      method: 'POST',
      body: form.value
    })
  }
  catch (e) {
    console.error('statusCode:', e.statusCode)
    console.error('statusMessage:', e.statusMessage)
    console.error('data:', e.data)
  }
}
```

Feedback much appreciated.

**Comment by Robinrrr** [comment]
@johannschopplich This is a really nice enhancement. It helps me to better differentiate my error cases. Thanks a lot for your effort!
